baseurl = "https://melcampbell1798.github.io/wedding-website"
title = "MC & AL"
author = "Melissa Campbell and Alex Lyons"
canonifyurls = true
languagecode = "en"
theme = "black-and-light"

pygmentsstyle       = "bw"
pygmentscodefences  = true

[params]
  sitename = "Alex & Melissa's Wedding"
  disableWebFonts = false

[[menu.main]]
    name = "Details"
    url  = "https://melcampbell1798.github.io/wedding-website/details"
[[menu.main]]
    name = "Registry"
    url  = "https://melcampbell1798.github.io/wedding-website/registry"
[[menu.main]]
    name = "RSVP"
    url  = "https://melcampbell1798.github.io/wedding-website/rsvp"
[[menu.main]]
    name = "Hotel"
    url  = "https://www.nantasketbeachresort.com/"